#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { buildIndexMarkdown, defaultProcessedSessionsState, ensureDirectoryPath, ensureLingxiLayout, processedSessionsPath, distillJournalPath } from "./_lingxi-memory.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const targetRoot = path.resolve(process.env.CODEX_PROJECT_DIR || process.cwd());

const VALID_HOSTS = new Set(["codex", "claude", "all"]);

function parseArgs(argv) {
  const args = { host: "all" };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--host" && argv[i + 1]) {
      args.host = argv[i + 1];
      i++;
    }
  }
  if (!VALID_HOSTS.has(args.host)) {
    process.stderr.write(`[lingxi-setup] Invalid --host value: "${args.host}". Must be one of: codex, claude, all\n`);
    process.exit(1);
  }
  return args;
}

function resolveTarget(...parts) {
  return path.join(targetRoot, ...parts);
}

function ensureDir(targetPath) {
  ensureDirectoryPath(targetPath);
}

function writeIfMissing(targetPath, content) {
  if (fs.existsSync(targetPath)) {
    return false;
  }
  ensureDir(path.dirname(targetPath));
  fs.writeFileSync(targetPath, content, "utf8");
  return true;
}

function writeManagedArtifact(targetPath, content) {
  ensureDir(path.dirname(targetPath));
  fs.writeFileSync(targetPath, content, "utf8");
  return true;
}

function renderTemplate(relativePath, replacements = {}) {
  const templatePath = path.join(repoRoot, "templates", ...relativePath.split("/"));
  let content = fs.readFileSync(templatePath, "utf8");
  for (const [key, value] of Object.entries(replacements)) {
    content = content.replaceAll(key, value);
  }
  return content;
}

// ---------------------------------------------------------------------------
// Shared utilities
// ---------------------------------------------------------------------------

function normalizeString(value) {
  return String(value || "").trim();
}

// ---------------------------------------------------------------------------
// Common layer: host-agnostic .lingxi/ initialization
// ---------------------------------------------------------------------------

function defaultAgentsMd() {
  return `# LingXi Runtime

This repository includes a local LingXi 2.0 runtime.

- Runtime root: \`.lingxi/\`
- Memory index: \`.lingxi/memory/INDEX.md\`
- Project memory notes: \`.lingxi/memory/project/\`
- Shared memory notes: \`.lingxi/memory/share/\`
- Distill state: \`.lingxi/state/processed-sessions.json\`
- Distill journal: \`.lingxi/state/distill-journal.jsonl\`
- Distill runner: \`node scripts/lx-distill-sessions.mjs\`

LingXi provides dedicated workflows for:

- task definition (\`task\`)
- task vetting (\`vet\`)

Global memory rule:

- Persist only durable, reusable engineering taste.
- Do not store one-off implementation details as memory.
- Exclude session-distill automation/self-distillation sessions from background memory selection.

Memory consumption rule:

- LingXi memory is injected automatically for meaningful repository turns through repo-local hooks when hooks are active.
- Apply only the smallest relevant memory set.
- Skip trivial or non-repository conversation turns.
`;
}

function setupCommon() {
  ensureLingxiLayout(targetRoot);

  writeIfMissing(
    resolveTarget(".lingxi", "memory", "INDEX.md"),
    buildIndexMarkdown([], targetRoot)
  );

  writeIfMissing(
    processedSessionsPath(targetRoot),
    JSON.stringify(defaultProcessedSessionsState(), null, 2) + "\n"
  );

  writeIfMissing(
    distillJournalPath(targetRoot),
    ""
  );

  const wroteAgentsMd = writeIfMissing(resolveTarget("AGENTS.md"), defaultAgentsMd());

  return { wroteAgentsMd };
}

// ---------------------------------------------------------------------------
// Codex adapter
// ---------------------------------------------------------------------------

const managedCodexHookCommand = "node \"$(git rev-parse --show-toplevel)/scripts/lx-memory-hook.mjs\"";
const windowsHooksNote = "Codex hooks are generated by setup, but the current Codex runtime does not execute hooks natively on Windows yet.";

function buildManagedCodexHooksConfig() {
  return {
    hooks: {
      UserPromptSubmit: [
        {
          hooks: [
            {
              type: "command",
              command: managedCodexHookCommand,
              statusMessage: "Loading LingXi memory"
            }
          ]
        }
      ]
    }
  };
}

function parseHookConfig(content, file) {
  let parsed;
  try {
    parsed = JSON.parse(content);
  } catch (error) {
    throw new Error(`Failed to parse ${file} as JSON: ${error.message}`);
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`${file} must contain a JSON object.`);
  }
  if (parsed.hooks != null && (typeof parsed.hooks !== "object" || Array.isArray(parsed.hooks))) {
    throw new Error(`${file}.hooks must be an object when present.`);
  }
  return parsed;
}

function isLingxiManagedCodexHook(handler) {
  return handler &&
    typeof handler === "object" &&
    normalizeString(handler.type) === "command" &&
    normalizeString(handler.command).includes("lx-memory-hook.mjs");
}

function mergeHookGroups(existingGroups, managedGroup) {
  const cleaned = [];
  for (const group of Array.isArray(existingGroups) ? existingGroups : []) {
    if (!group || typeof group !== "object" || Array.isArray(group)) continue;
    const hooks = Array.isArray(group.hooks) ? group.hooks.filter((hook) => !isLingxiManagedCodexHook(hook)) : [];
    if (hooks.length === 0) continue;
    cleaned.push({
      ...group,
      hooks
    });
  }
  cleaned.push(managedGroup);
  return cleaned;
}

function mergeCodexHooksConfig(existingContent = null) {
  const config = existingContent
    ? parseHookConfig(existingContent, ".codex/hooks.json")
    : {};
  const hooks = config.hooks && typeof config.hooks === "object" && !Array.isArray(config.hooks)
    ? { ...config.hooks }
    : {};
  hooks.UserPromptSubmit = mergeHookGroups(hooks.UserPromptSubmit, buildManagedCodexHooksConfig().hooks.UserPromptSubmit[0]);
  return JSON.stringify({
    ...config,
    hooks
  }, null, 2) + "\n";
}

function mergeCodexTomlConfig(existingContent = "") {
  const lines = existingContent === "" ? [] : existingContent.replace(/\r\n/g, "\n").split("\n");
  const output = [];
  let inFeatures = false;
  let featuresSeen = false;
  let codexHooksWritten = false;

  const flushCodexHooks = () => {
    if (inFeatures && !codexHooksWritten) {
      output.push("codex_hooks = true");
      codexHooksWritten = true;
    }
  };

  lines.forEach((line) => {
    const sectionMatch = /^\s*\[([^\]]+)\]\s*$/.exec(line);
    if (sectionMatch) {
      flushCodexHooks();
      inFeatures = sectionMatch[1] === "features";
      if (inFeatures) {
        featuresSeen = true;
      }
      output.push(line);
      return;
    }

    if (inFeatures && /^\s*codex_hooks\s*=/.test(line)) {
      output.push("codex_hooks = true");
      codexHooksWritten = true;
      return;
    }

    output.push(line);
  });

  flushCodexHooks();

  if (!featuresSeen) {
    if (output.length > 0 && output[output.length - 1] !== "") {
      output.push("");
    }
    output.push("[features]");
    output.push("codex_hooks = true");
  }

  return `${output.join("\n").replace(/\n*$/, "\n")}`;
}

function cleanupLegacyAutomation() {
  const automationToml = resolveTarget(".lingxi", "setup", "automation.session-distill.toml");
  if (fs.existsSync(automationToml)) {
    fs.unlinkSync(automationToml);
  }
}

function setupCodexAdapter() {
  cleanupLegacyAutomation();

  writeManagedArtifact(
    resolveTarget(".codex", "agents", "lingxi-session-distill.toml"),
    renderTemplate("agents/lingxi-session-distill.toml.tmpl")
  );

  const codexConfigPath = resolveTarget(".codex", "config.toml");
  const existingCodexConfig = fs.existsSync(codexConfigPath) ? fs.readFileSync(codexConfigPath, "utf8") : "";
  writeManagedArtifact(codexConfigPath, mergeCodexTomlConfig(existingCodexConfig));

  const codexHooksPath = resolveTarget(".codex", "hooks.json");
  const existingCodexHooks = fs.existsSync(codexHooksPath) ? fs.readFileSync(codexHooksPath, "utf8") : null;
  writeManagedArtifact(codexHooksPath, mergeCodexHooksConfig(existingCodexHooks));
}

// ---------------------------------------------------------------------------
// Claude adapter
// ---------------------------------------------------------------------------

const managedClaudeHookCommand = "node \"$CLAUDE_PROJECT_DIR/scripts/lx-memory-hook.mjs\"";

function isLingxiManagedClaudeHook(handler) {
  if (!handler || typeof handler !== "object" || normalizeString(handler.type) !== "command") return false;
  const cmd = normalizeString(handler.command);
  return cmd.includes("lx-memory-hook.mjs") || cmd.includes("lx-memory-hook-claude.mjs");
}

function mergeClaudeHookGroups(existingGroups, managedGroup) {
  const cleaned = [];
  for (const group of Array.isArray(existingGroups) ? existingGroups : []) {
    if (!group || typeof group !== "object" || Array.isArray(group)) continue;
    const hooks = Array.isArray(group.hooks) ? group.hooks.filter((hook) => !isLingxiManagedClaudeHook(hook)) : [];
    if (hooks.length === 0) continue;
    cleaned.push({
      ...group,
      hooks
    });
  }
  cleaned.push(managedGroup);
  return cleaned;
}

function buildManagedClaudeHookGroup() {
  return {
    matcher: "",
    hooks: [
      {
        type: "command",
        command: managedClaudeHookCommand,
        statusMessage: "Loading LingXi memory"
      }
    ]
  };
}

function mergeClaudeSettingsJson(existingContent = null) {
  let config = {};
  if (existingContent) {
    try {
      config = JSON.parse(existingContent);
    } catch (error) {
      throw new Error(`Failed to parse .claude/settings.json as JSON: ${error.message}`);
    }
    if (!config || typeof config !== "object" || Array.isArray(config)) {
      config = {};
    }
  }

  const hooks = (config.hooks && typeof config.hooks === "object" && !Array.isArray(config.hooks))
    ? { ...config.hooks }
    : {};

  hooks.UserPromptSubmit = mergeClaudeHookGroups(hooks.UserPromptSubmit, buildManagedClaudeHookGroup());

  return JSON.stringify({
    ...config,
    hooks
  }, null, 2) + "\n";
}

function defaultClaudeMd() {
  return `# LingXi Runtime (Claude Code)

@AGENTS.md

## Claude Code Notes

- Skills are available under \`.claude/skills/\`
- Memory hook runs on UserPromptSubmit via \`.claude/settings.json\`
- Background session distill agent: \`.claude/agents/lingxi-session-distill.md\`
- Distill state: \`.lingxi/state/processed-sessions.json\`
`;
}

function copySkillsToClaudeDir() {
  const skillsSrc = path.join(repoRoot, "skills");
  const skillsDst = resolveTarget(".claude", "skills");

  if (!fs.existsSync(skillsSrc)) return;

  ensureDir(skillsDst);

  const skillDirs = fs.readdirSync(skillsSrc, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  for (const skillName of skillDirs) {
    const src = path.join(skillsSrc, skillName);
    const dst = path.join(skillsDst, skillName);
    copyDirRecursive(src, dst);
  }
}

function copyDirRecursive(src, dst) {
  ensureDir(dst);
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const dstPath = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, dstPath);
    } else {
      fs.copyFileSync(srcPath, dstPath);
    }
  }
}

function cleanupLegacyCronPending() {
  for (const name of ["claude-cron-pending.json", "claude-cron-state.json"]) {
    const filePath = resolveTarget(".lingxi", "setup", name);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  }
}

function setupClaudeAdapter() {
  cleanupLegacyCronPending();
  // .claude/agents/lingxi-session-distill.md
  writeManagedArtifact(
    resolveTarget(".claude", "agents", "lingxi-session-distill.md"),
    renderTemplate("agents/lingxi-session-distill.claude.md.tmpl")
  );

  // .claude/settings.json (merge hooks)
  const claudeSettingsPath = resolveTarget(".claude", "settings.json");
  const existingClaudeSettings = fs.existsSync(claudeSettingsPath) ? fs.readFileSync(claudeSettingsPath, "utf8") : null;
  writeManagedArtifact(claudeSettingsPath, mergeClaudeSettingsJson(existingClaudeSettings));

  // .claude/skills/ (copy from skills/)
  copySkillsToClaudeDir();

  // CLAUDE.md (only when missing)
  const wroteClaudeMd = writeIfMissing(resolveTarget("CLAUDE.md"), defaultClaudeMd());

  return { wroteClaudeMd };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const args = parseArgs(process.argv.slice(2));
  const host = args.host;

  const commonResult = setupCommon();

  const codexEnabled = host === "codex" || host === "all";
  const claudeEnabled = host === "claude" || host === "all";

  if (codexEnabled) {
    setupCodexAdapter();
  }

  let claudeResult = null;
  if (claudeEnabled) {
    claudeResult = setupClaudeAdapter();
  }

  const wroteAgentsMd = commonResult.wroteAgentsMd;
  const wroteClaudeMd = claudeResult ? claudeResult.wroteClaudeMd : false;

  const summary = {
    target_root: targetRoot,
    host,
    created_runtime_root: fs.existsSync(resolveTarget(".lingxi")),
    wrote_agents_md: wroteAgentsMd,
    wrote_claude_md: wroteClaudeMd,
    codex_enabled: codexEnabled,
    claude_enabled: claudeEnabled,
    files: [
      ".lingxi/memory/INDEX.md",
      ".lingxi/state/processed-sessions.json",
      ".lingxi/state/distill-journal.jsonl",
      ...(codexEnabled ? [
        ".codex/config.toml",
        ".codex/hooks.json",
        ".codex/agents/lingxi-session-distill.toml"
      ] : []),
      ...(claudeEnabled ? [
        ".claude/settings.json",
        ".claude/agents/lingxi-session-distill.md",
        ".claude/skills/"
      ] : [])
    ],
    ...(codexEnabled ? {
      codex_hooks_enabled: true,
      codex_hooks_windows_note: windowsHooksNote
    } : {})
  };

  process.stdout.write(JSON.stringify(summary, null, 2) + "\n");
}

main();
