#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { buildIndexMarkdown, defaultProcessedSessionsState, ensureDirectoryPath, ensureLingxiLayout, processedSessionsPath, distillJournalPath } from "./_lingxi-memory.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const targetRoot = path.resolve(process.env.CODEX_PROJECT_DIR || process.cwd());

function resolveTarget(...parts) {
  return path.join(targetRoot, ...parts);
}

function ensureDir(targetPath) {
  ensureDirectoryPath(targetPath);
}

function writeIfMissing(targetPath, content) {
  if (fs.existsSync(targetPath)) {
    return false;
  }
  ensureDir(path.dirname(targetPath));
  fs.writeFileSync(targetPath, content, "utf8");
  return true;
}

function writeManagedArtifact(targetPath, content) {
  ensureDir(path.dirname(targetPath));
  fs.writeFileSync(targetPath, content, "utf8");
  return true;
}

function renderTemplate(relativePath, replacements = {}) {
  const templatePath = path.join(repoRoot, "templates", ...relativePath.split("/"));
  let content = fs.readFileSync(templatePath, "utf8");
  for (const [key, value] of Object.entries(replacements)) {
    content = content.replaceAll(key, value);
  }
  return content;
}

const managedHookCommand = "node \"$(git rev-parse --show-toplevel)/scripts/lx-memory-hook.mjs\"";
const windowsHooksNote = "Codex hooks are generated by setup, but the current Codex runtime does not execute hooks natively on Windows yet.";

function buildManagedHooksConfig() {
  return {
    hooks: {
      UserPromptSubmit: [
        {
          hooks: [
            {
              type: "command",
              command: managedHookCommand,
              statusMessage: "Loading LingXi memory"
            }
          ]
        }
      ]
    }
  };
}

function parseHookConfig(content, file) {
  let parsed;
  try {
    parsed = JSON.parse(content);
  } catch (error) {
    throw new Error(`Failed to parse ${file} as JSON: ${error.message}`);
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`${file} must contain a JSON object.`);
  }
  if (parsed.hooks != null && (typeof parsed.hooks !== "object" || Array.isArray(parsed.hooks))) {
    throw new Error(`${file}.hooks must be an object when present.`);
  }
  return parsed;
}

function isLingxiManagedHook(handler) {
  return handler &&
    typeof handler === "object" &&
    normalizeString(handler.type) === "command" &&
    normalizeString(handler.command).includes("lx-memory-hook.mjs");
}

function normalizeString(value) {
  return String(value || "").trim();
}

function mergeHookGroups(existingGroups, managedGroup) {
  const cleaned = [];
  for (const group of Array.isArray(existingGroups) ? existingGroups : []) {
    if (!group || typeof group !== "object" || Array.isArray(group)) continue;
    const hooks = Array.isArray(group.hooks) ? group.hooks.filter((hook) => !isLingxiManagedHook(hook)) : [];
    if (hooks.length === 0) continue;
    cleaned.push({
      ...group,
      hooks
    });
  }
  cleaned.push(managedGroup);
  return cleaned;
}

function mergeHooksConfig(existingContent = null) {
  const config = existingContent
    ? parseHookConfig(existingContent, ".codex/hooks.json")
    : {};
  const hooks = config.hooks && typeof config.hooks === "object" && !Array.isArray(config.hooks)
    ? { ...config.hooks }
    : {};
  hooks.UserPromptSubmit = mergeHookGroups(hooks.UserPromptSubmit, buildManagedHooksConfig().hooks.UserPromptSubmit[0]);
  return JSON.stringify({
    ...config,
    hooks
  }, null, 2) + "\n";
}

function mergeCodexConfig(existingContent = "") {
  const lines = existingContent === "" ? [] : existingContent.replace(/\r\n/g, "\n").split("\n");
  const output = [];
  let inFeatures = false;
  let featuresSeen = false;
  let codexHooksWritten = false;

  const flushCodexHooks = () => {
    if (inFeatures && !codexHooksWritten) {
      output.push("codex_hooks = true");
      codexHooksWritten = true;
    }
  };

  lines.forEach((line) => {
    const sectionMatch = /^\s*\[([^\]]+)\]\s*$/.exec(line);
    if (sectionMatch) {
      flushCodexHooks();
      inFeatures = sectionMatch[1] === "features";
      if (inFeatures) {
        featuresSeen = true;
      }
      output.push(line);
      return;
    }

    if (inFeatures && /^\s*codex_hooks\s*=/.test(line)) {
      output.push("codex_hooks = true");
      codexHooksWritten = true;
      return;
    }

    output.push(line);
  });

  flushCodexHooks();

  if (!featuresSeen) {
    if (output.length > 0 && output[output.length - 1] !== "") {
      output.push("");
    }
    output.push("[features]");
    output.push("codex_hooks = true");
  }

  return `${output.join("\n").replace(/\n*$/, "\n")}`;
}

function writeMergedCodexConfig(targetPath) {
  const existing = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, "utf8") : "";
  return writeManagedArtifact(targetPath, mergeCodexConfig(existing));
}

function writeMergedHooksConfig(targetPath) {
  const existing = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, "utf8") : null;
  return writeManagedArtifact(targetPath, mergeHooksConfig(existing));
}

function defaultAgentsMd() {
  return `# LingXi Runtime

This repository includes a local LingXi 2.0 runtime.

- Runtime root: \`.lingxi/\`
- Memory index: \`.lingxi/memory/INDEX.md\`
- Project memory notes: \`.lingxi/memory/project/\`
- Shared memory notes: \`.lingxi/memory/share/\`
- Distill state: \`.lingxi/state/processed-sessions.json\`
- Distill journal: \`.lingxi/state/distill-journal.jsonl\`
- Codex hook config: \`.codex/config.toml\`
- Codex hook definitions: \`.codex/hooks.json\`
- Background agent definition: \`.codex/agents/lingxi-session-distill.toml\`
- Generated automation config: \`.lingxi/setup/automation.session-distill.toml\`
- Codex distill runner: \`node scripts/lx-distill-sessions.mjs\`

LingXi provides dedicated workflows for:

- task definition (\`task\`)
- task vetting (\`vet\`)

Global memory rule:

- Persist only durable, reusable engineering taste.
- Do not store one-off implementation details as memory.
- Exclude session-distill automation/self-distillation sessions from background memory selection.
- Treat \`.codex/agents/\` and generated automation artifacts as Codex runtime adapters over LingXi memory core.

Memory consumption rule:

- LingXi memory is injected automatically for meaningful repository turns through repo-local Codex hooks when hooks are active.
- Apply only the smallest relevant memory set.
- Skip trivial or non-repository conversation turns.
- ${windowsHooksNote}
`;
}

function main() {
  ensureLingxiLayout(targetRoot);

  writeIfMissing(
    resolveTarget(".lingxi", "memory", "INDEX.md"),
    buildIndexMarkdown([], targetRoot)
  );

  writeIfMissing(
    processedSessionsPath(targetRoot),
    JSON.stringify(defaultProcessedSessionsState(), null, 2) + "\n"
  );

  writeIfMissing(
    distillJournalPath(targetRoot),
    ""
  );

  writeManagedArtifact(
    resolveTarget(".codex", "agents", "lingxi-session-distill.toml"),
    renderTemplate("agents/lingxi-session-distill.toml.tmpl")
  );

  writeMergedCodexConfig(resolveTarget(".codex", "config.toml"));
  writeMergedHooksConfig(resolveTarget(".codex", "hooks.json"));

  writeManagedArtifact(
    resolveTarget(".lingxi", "setup", "automation.session-distill.toml"),
    renderTemplate("automations/session-distill.toml.tmpl", {
      "__PROJECT_ROOT__": targetRoot
    })
  );

  const agentsMdPath = resolveTarget("AGENTS.md");
  const wroteAgentsMd = writeIfMissing(agentsMdPath, defaultAgentsMd());

  const summary = {
    target_root: targetRoot,
    created_runtime_root: fs.existsSync(resolveTarget(".lingxi")),
    wrote_agents_md: wroteAgentsMd,
    default_distill_rrule: "FREQ=HOURLY;INTERVAL=6",
    automation_registration_required: true,
    automation_create_command: "node scripts/lx-create-automation.mjs",
    codex_hooks_enabled: true,
    codex_hooks_windows_note: windowsHooksNote,
    files: [
      ".lingxi/memory/INDEX.md",
      ".lingxi/state/processed-sessions.json",
      ".lingxi/state/distill-journal.jsonl",
      ".codex/config.toml",
      ".codex/hooks.json",
      ".codex/agents/lingxi-session-distill.toml",
      ".lingxi/setup/automation.session-distill.toml"
    ]
  };

  process.stdout.write(JSON.stringify(summary, null, 2) + "\n");
}

main();
